use_frameworks!

platform :ios, '10.0'

target 'FWAmarFramewokrFromGitOnly_Example' do
  pod 'FWAmarFramewokrFromGitOnly', :path => '../'

  target 'FWAmarFramewokrFromGitOnly_Tests' do
    inherit! :search_paths

    
  end
end
